import { url } from '../utilidades/ayudas';

export default [
  `${url}/capa2/distorsion_movimiento_1.mp4`,
  `${url}/capa2/distorsion_movimiento_2.mp4`,
  `${url}/capa2/tipo_gif_cuadrado.mp4`,
  `${url}/capa2/tren.mp4`,
  `${url}/capa2/agua.mp4`,
  `${url}/capa2/angel_niebla.mp4`,
  `${url}/capa2/arbole_niebla.mp4`,
  `${url}/capa2/arbol_fiesta_mudo.mp4`,
  `${url}/capa2/arbol_viento.mp4`,
  `${url}/capa2/borbullas.mp4`,
  `${url}/capa2/flores_color_gif.mp4`,
  `${url}/capa2/flores_pb_gif_2.mp4`,
  `${url}/capa2/foot_luz.mp4`,
  `${url}/capa2/monstro.mp4`,
  `${url}/capa2/open.mp4`,
  `${url}/capa2/cortina_nb.mp4`,
  `${url}/capa2/pixel.mp4`,
  `${url}/capa2/pombos_1.mp4`,
  `${url}/capa2/reflejo_pomba.mp4`,
  `${url}/capa2/sao_paulo.mp4`,
  `${url}/capa2/sone_contigo_film.mp4`,
  `${url}/capa2/ventana_lluvia.mp4`,
  `${url}/capa2/ventana_noche.mp4`,
  `${url}/capa2/ventana_poligono.mp4`,
  `${url}/capa2/ventana_puente.mp4`,
  `${url}/capa2/ventana_roja.mp4`,
  `${url}/capa2/ventana_tajo.mp4`,
  `${url}/capa2/ventana_tren_1.mp4`,
  `${url}/capa2/ventana_tren_2.mp4`,
  `${url}/capa2/avion_navidad.mp4`,
  `${url}/capa2/coche_aeropuerto.mp4`,
  `${url}/capa2/sants_sol.mp4`,
];
